stages:
  - build
  - deploy

build:
  image: node:latest    # Run the job in a `node` docker image
  stage: build
  script:
    - npm install      # Run `yarn install` and `yarn build`
    - npm run build
  artifacts:
    paths:
      - dist/          # Save the build result as an artfact

# Stages run sequentially, so we add a new `deploy` stage 
# after the `build` one

pages:
  image: alpine:latest
  stage: deploy
  variables:
    GIT_STRATEGY: none        # Do not clone git repo
    PUBLIC_URL: https://errityr.gricad-pages.univ-grenoble-alpes.fr/www-ww2heritage/
  script:
    # Rename the CRA `build` folder to `public`
    - mv dist public         
  artifacts:
    paths:
      - public