INSERT INTO ui_column_names (Header, accessor) values ('ID', 'id');
INSERT INTO ui_column_names (Header, accessor) values ('Name', 'name');
INSERT INTO ui_column_names (Header, accessor) values ('Alt. Name 1', 'alt_name');
INSERT INTO ui_column_names (Header, accessor) values ('Alt. Name 2', 'alt_name_1');
INSERT INTO ui_column_names (Header, accessor) values ('Town', 'town');
INSERT INTO ui_column_names (Header, accessor) values ('Country', 'country');
INSERT INTO ui_column_names (Header, accessor) values ('Region', 'region');
INSERT INTO ui_column_names (Header, accessor) values ('Province', 'province');
INSERT INTO ui_column_names (Header, accessor) values ('Notes', 'notes');
INSERT INTO ui_column_names (Header, accessor) values ('Period', 'period');
INSERT INTO ui_column_names (Header, accessor) values ('Period 2', 'period_2');
INSERT INTO ui_column_names (Header, accessor) values ('Associated With', 'associated_with');
INSERT INTO ui_column_names (Header, accessor) values ('Has Damaged Bibliography?', 'damaged_bibliography');
INSERT INTO ui_column_names (Header, accessor) values ('Known Damage', 'known_damage');
INSERT INTO ui_column_names (Header, accessor) values ('Photograph Links', 'photograph_links');
INSERT INTO ui_column_names (Header, accessor) values ('GE OSM Co-ords', 'coordinates_ge_osm');
INSERT INTO ui_column_names (Header, accessor) values ('S-Centre', 's_centre');
INSERT INTO ui_column_names (Header, accessor) values ('Polygon GE Co-ords', 'coordinates_polygon_ge');
INSERT INTO ui_column_names (Header, accessor) values ('Georectified Centre Co-ords', 'coordinates_centre_georectified');
INSERT INTO ui_column_names (Header, accessor) values ('Georectified Polygon Co-ords', 'coordinates_polygon_georectified');
INSERT INTO ui_column_names (Header, accessor) values ('Acrhives List', 'archives_list');
INSERT INTO ui_column_names (Header, accessor) values ('Arcives List Text', 'archives_list_text');
INSERT INTO ui_column_names (Header, accessor) values ('Harvard Long List', 'harvard_long_list');
INSERT INTO ui_column_names (Header, accessor) values ('Harvard Long List Stars', 'harvard_long_list_stars');
INSERT INTO ui_column_names (Header, accessor) values ('Harvard Long List Text', 'harvard_long_list_text');
INSERT INTO ui_column_names (Header, accessor) values ('Harvard Short List', 'harvard_short_list');
INSERT INTO ui_column_names (Header, accessor) values ('Harvard Short List Text', 'harvard_short_list_text');
INSERT INTO ui_column_names (Header, accessor) values ('ACLS Map Name', 'acls_map_name');
INSERT INTO ui_column_names (Header, accessor) values ('ACLS Map Type', 'acls_map_type');
INSERT INTO ui_column_names (Header, accessor) values ('ACLS Map Stars', 'acls_map_stars');
INSERT INTO ui_column_names (Header, accessor) values ('ACLS Map Grid Reference', 'acls_map_grid_reference');
INSERT INTO ui_column_names (Header, accessor) values ('ACLS Map Address', 'acls_map_address');
INSERT INTO ui_column_names (Header, accessor) values ('ACLS Map Text', 'acls_map_text');
INSERT INTO ui_column_names (Header, accessor) values ('ACLS Map Image Links', 'acls_map_image_links');
INSERT INTO ui_column_names (Header, accessor) values ('ACS Map Image Links', 'acs_map_image_links');
INSERT INTO ui_column_names (Header, accessor) values ('ACLS Atlas Title', 'acls_atlas_title');
INSERT INTO ui_column_names (Header, accessor) values ('ACLS Atlas Type', 'acls_atlas_type');
INSERT INTO ui_column_names (Header, accessor) values ('ACLS Atlas Stars', 'acls_atlas_stars');
INSERT INTO ui_column_names (Header, accessor) values ('ACLS Atlas Grid Reference', 'acls_atlas_grid_reference');
INSERT INTO ui_column_names (Header, accessor) values ('ACLS Atlas Address', 'acls_atlas_address');
INSERT INTO ui_column_names (Header, accessor) values ('CA Atlas Text', 'ca_atlas_text');
INSERT INTO ui_column_names (Header, accessor) values ('CA Handbook', 'ca_handbook');
INSERT INTO ui_column_names (Header, accessor) values ('CA Handbook Type', 'ca_handbook_type');
INSERT INTO ui_column_names (Header, accessor) values ('CA Handbook Stars', 'ca_handbook_stars');
INSERT INTO ui_column_names (Header, accessor) values ('CA Handbook Address', 'ca_handbook_address');
INSERT INTO ui_column_names (Header, accessor) values ('CA Handbook Text', 'ca_handbook_text');
INSERT INTO ui_column_names (Header, accessor) values ('LPM Volume', 'lpm_vol');
INSERT INTO ui_column_names (Header, accessor) values ('LPM Stars', 'lpm_stars');
INSERT INTO ui_column_names (Header, accessor) values ('LPM Military Grid', 'lpm_military_grid');
INSERT INTO ui_column_names (Header, accessor) values ('LPM Text', 'lpm_text');
INSERT INTO ui_column_names (Header, accessor) values ('Zone Handbook Volume', 'zone_handbook_vol');
INSERT INTO ui_column_names (Header, accessor) values ('Zone Handbook Aux. List', 'zone_handbook_aux_list');
INSERT INTO ui_column_names (Header, accessor) values ('Zone Handbook Text', 'zone_hb_text');